apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: portefaix-M0002
  annotations:
    policies.kyverno.io/title: portefaix-M0002
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Metadata should have all the expected a8r.io annotations
      See: https://ambassadorlabs.github.io/k8s-for-humans/
spec:
  validationFailureAction: audit
  rules:
  - name: check-for-a8r.io-annotations
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "a8r.io annotations is required."
      pattern:
        metadata:
          annotations:
            a8r.io/description: "?*"
            a8r.io/owner: "?*"
            a8r.io/bugs: "?*"
            a8r.io/documentation: "?*"
            a8r.io/repository: "?*"
            a8r.io/support: "?*"
